#!/usr/bin/env bash
# LUKSUS
# Easy drive encryption script using LUKS
# by Thomas Frivold
#
# github code repository (project page):
# https://github.com/thomasfrivold/luksus
#
# please see README file for complete information
# regarding LUKSUS
# 
# LUKSUS is released under GNU GPLv2 License
# see URL below
# http://www.gnu.org/licenses/gpl-2.0.html 

###############################
######### VARIABLES ###########
###############################

if [ -r LUKSUS.variables ]; then
	source LUKSUS.variables
else
	exit 0
fi

###############################
#####    FUNCTIONS       ######
###############################


if [ -r LUKSUS.functions ]; then
	source LUKSUS.functions
else
	exit 0
fi


###############################
###### INITIAL WELCOME ########
###############################

if [ -r LUKSUS.welcome ]; then
	source LUKSUS.welcome
else
	exit 0
fi


###############################
##### CONDITIONAL CHECKS ######
###############################


if [ -r LUKSUS.checks ]; then
	source LUKSUS.checks
else
	exit 0
fi


#########################################################
#########################################################
#########################################################
#########################################################
################ BEGINNING PROGRAM ######################
#########################################################
#########################################################
#########################################################
#########################################################

# Calling functions
DISPLAYLOGO
ASKUSERVERIFY
LOOPBACKMETHOD
DONTSHREDIFLOOPBACK
THESECRETSAUCE
CREATEANDMOUNTFS
DISPLAYLOGO
DISPLAYSUMMARY
exit 0
